## Variables and data types

In [ ]:
x=5
x

5

In [ ]:
x+2

7

In [ ]:
x-2

3

In [ ]:
x*2

10

In [ ]:
x**2

25

In [ ]:
x%2

1

In [ ]:
x/2

2.5

In [ ]:
x/float(2)

2.5

In [ ]:
str=('5','3.45','True')
print('str=',str)

str= ('5', '3.45', 'True')


In [ ]:
#variable to integer
int=5,3,1
print(int)

(5, 3, 1)


In [ ]:
#variable to float
float=5.0,1.0
print(float)


(5.0, 1.0)


In [ ]:
#variable to booleans
bool=True, True, True
print(bool)

(True, True, True)


In [ ]:
help(str)

Help on tuple object:

class tuple(object)
 |  tuple() -> empty tuple
 |  tuple(iterable) -> tuple initialized from iterable's items
 |  
 |  If the argument is a tuple, the return value is the same object.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __getnewargs__(...)
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __iter__(self, /)
 |      Implement iter(self).
 |  
 |  __le__(self, value, /)
 |      Return self<=value.
 |  
 |  __len__(self, /)
 |      Return len(self).
 |  
 |  __lt__(self, value, /)
 |      Return self<value.
 |  
 |  _

### String operations

In [ ]:
my_string = 'thisStringIsAwesome'
my_string 

'thisStringIsAwesome'

In [ ]:
my_string * 2

'thisStringIsAwesomethisStringIsAwesome'

In [ ]:
my_string + 'Innit'

'thisStringIsAwesomeInnit'

In [ ]:
'm' in my_string

True

# Lists

In [ ]:
 a = 'is'
 b = 'nice'
 my_list = ['my', 'list', a, b]
 my_list2 = [[4,5,6,7], [3,4,5,6]]

In [ ]:
my_list[1]

'list'

In [ ]:
my_list[-3]

'list'

In [ ]:
my_list[2]

'is'

In [ ]:
my_list[-1]

'nice'

In [ ]:
my_list[0]

'my'

In [ ]:
my_list[1:3]


['list', 'is']

In [ ]:
 my_list[1:]


['list', 'is', 'nice']

In [ ]:
 my_list[:3]


['my', 'list', 'is']

In [ ]:
 my_list[:]

['my', 'list', 'is', 'nice']

In [ ]:
my_list2[1][0]


3

In [ ]:
 my_list2[1][:2]

[3, 4]

List operations

In [ ]:
my_list + my_list

['my', 'list', 'is', 'nice', 'my', 'list', 'is', 'nice']

In [ ]:
 my_list * 2

['my', 'list', 'is', 'nice', 'my', 'list', 'is', 'nice']

In [ ]:
my_list2 > 4

False

In [ ]:
my_list2 > 1

True

In [ ]:
my_list2 < 4

True

List Methods

In [ ]:
my_list.index(a)


2

In [ ]:
my_list.count(a)


1

In [ ]:
 my_list.append('!')

In [ ]:
 my_list.remove('!')

In [ ]:
del(my_list[0:1])

In [ ]:
 my_list.reverse()


In [ ]:
 my_list.extend('!')


In [ ]:
 my_list.pop(-1)


'!'

In [ ]:
 my_list.insert(0,'!')


In [ ]:
 my_list.sort()

String operations

In [ ]:
my_string[3]


's'

In [ ]:
my_string[4:9]

'Strin'

String methods

In [ ]:
my_string.upper()


'THISSTRINGISAWESOME'

In [ ]:
 my_string.lower()


'thisstringisawesome'

In [ ]:

my_string.count('w')


1

In [ ]:
my_string.replace('e', 'i')


'thisStringIsAwisomi'

In [ ]:
my_string.strip()

'thisStringIsAwesome'

## Libraries

In [ ]:
import numpy
import numpy as np

In [ ]:
from math import pi

### Numpy Arrays 

In [ ]:
my_list = [1, 2, 3, 4]
my_array = np.array(my_list)
my_2darray = np.array([[1,2,3],[4,5,6]])


In [ ]:
my_array[1]


2

In [ ]:
 my_array[0:2]


array([1, 2])

In [ ]:
my_2darray[:,0]

array([1, 4])

Numpy array operations

In [ ]:
my_array > 3

array([False, False, False,  True])

In [ ]:
my_array*2

array([2, 4, 6, 8])

In [ ]:
my_array + np.array([5, 6, 7, 8])


array([ 6,  8, 10, 12])

In [ ]:
my_array.shape


(4,)

In [ ]:
 np.append(other_array)


NameError: ignored

In [ ]:
np.insert(my_array, 1, 5)


array([1, 5, 2, 3, 4])

In [ ]:
 np.delete(my_array,[1])


array([1, 3, 4])

In [ ]:
 np.mean(my_array)

2.5

In [ ]:
 np.median(my_array)


2.5

In [ ]:
 my_array.corrcoef()


AttributeError: ignored

In [ ]:
 np.std(my_array)

1.118033988749895